AUR Update via supported helper if pamac is not installed
In case pamac-common is not installed, update the AUR via available helpers provided by pacui functionality

diff --git a/manjaro_update b/manjaro_update
--- a/manjaro_update
+++ b/manjaro_update
@@ -5,7 +5,145 @@ SHELL=/usr/bin/bash
 # the alternative package managers - Pamac, Snap and Flatpak in a automatic
 # manner, with as little as necessary user intervention required.
 # It makes use of the functionality of PacUI for the system maintance.
+#
+# Update System
+_update() {
+        # define local variable, which indicates whether the installation process was successful or not.
+        local install_successful
 
+        if [[ "$AUR_Helper" == "yay" ]]                                             # check, if $AUR_Helper variable is set to "aurman". ATTENTION: sometimes, this requires   [[ "$AUR_Helper" == "aurman" ]]   and sometimes   test '$AUR_Helper' = "aurman"  . i do not know why this is the case.
+        then
+
+            # execute "yay -Syu" command:
+            if ( yay "$argument_flag"-Syu )                                         # execute command "yay -Syu". if this command fails "false" is returned and the result is: "if ( false )"
+            then
+                # only set $install_successful=true, if the command "yay -Syu" was executed without errors
+                install_successful=true
+            else
+                install_successful=false
+            fi
+
+        elif [[ "$AUR_Helper" == "pikaur" ]]
+        then
+
+            # execute "pikaur -Syu" command:
+            if ( pikaur "$argument_flag"-Syu )
+            then
+                # only set $install_successful=true, if the command "pikaur -Syu" was executed without errors
+                install_successful=true
+            else
+                install_successful=false
+            fi
+
+        elif [[ "$AUR_Helper" == "aurman" ]]
+        then
+
+            # execute "aurman -Syu" command:
+            if ( aurman "$argument_flag"-Syu )
+            then
+                # only set $install_successful=true, if the command "aurman -Syu" was executed without errors
+                install_successful=true
+            else
+                install_successful=false
+            fi
+
+        elif [[ "$AUR_Helper" == "pakku" ]]
+        then
+
+            # execute "pakku -Syu" command:
+            if ( pakku "$argument_flag"-Syu )
+            then
+                # only set $install_successful=true, if the command "pakku -Syu" was executed without errors
+                install_successful=true
+            else
+                install_successful=false
+            fi
+
+        elif [[ "$AUR_Helper" == "trizen" ]]
+        then
+
+            # execute "trizen -Syu" command:
+            if ( trizen "$argument_flag"-Syu )
+            then
+                # only set $install_successful=true, if the command "trizen -Syu" was executed without errors
+                install_successful=true
+            else
+                install_successful=false
+            fi
+
+        elif [[ "$AUR_Helper" == "pacaur" ]]
+        then
+
+            # execute "pacaur -Syu --color always" command:
+            if ( pacaur "$argument_flag"-Syu --color always )
+            then
+                # only set $install_successful=true, if the command "pacaur -Syu --color always" was executed without errors
+                install_successful=true
+            else
+                install_successful=false
+            fi
+
+        else
+
+            # execute "sudo pacman -Syu --color always" command:
+            if ( sudo pacman "$argument_flag"-Syu --color always )
+            then
+                # only set $install_successful=true, if the command "sudo pacman -Syu --color always" was executed without errors
+                install_successful=true
+            else
+                install_successful=false
+            fi
+
+        fi
+
+        # if one of the above update commands has failed, the following if-statement is true:
+        if [[ "$install_successful" == "false" ]]
+        then
+
+            local server
+            # extract mirror/repository server url from /etc/pacman.d/mirrorlist file with command:
+            server="$( grep "^Server =" -m 1 "/etc/pacman.d/mirrorlist" |awk -F '=' '{print $2}' | awk -F '$' '{print $1}' )"
+
+            # if one of the above update commands has failed, there are multiple points of failure. the first one is the internet/repository/mirror connection of the user:
+            # check, whether there is a connection to the mirror/repository server. this is needed for package download/update!
+            if ( curl --silent --fail  $(echo "$server") &>/dev/null )                      # the "curl --silent --fail" command gets executed in any case in order to check its output.
+            then
+
+                # next, we can force the update, but only for packages from the system repositories and not packages from the AUR. this means, we make sure package updates from system repositories fail:
+                if ! ( sudo pacman -Syu --color always )                            # the "sudo pacman -Syu --color always" command gets executed in any case in order to check its output.
+                then
+
+                    # now, we are sure there is an active connection to the server/mirror/repository and package updates from there have failed. in this case, we can offer the user to forcefully install updates:
+                    local answer
+                    # ask, whether to force update the system and save answer in "answer" variable:
+                    echo -e " \e[1m Updates from system repositories have failed probably because of file conflicts. \e[0m"
+                    echo -e " \e[41m Do you want to forcefully overwrite all conflicting files? [y|N] \e[0m"
+                    read -r -n 1 -e answer                                          # this "read" command only accepts 1 letter as answer. this feels faster and is enough in this situation.
+
+                    case ${answer:-n} in                                            # if ENTER is pressed, the variable "answer" is empty. if "answer" is empty, its default value is "n".
+                        y|Y|yes|Yes|YES )                                           # do this, if "answer" is y or Y or yes or Yes or YES
+                            sudo pacman -Syu --color always --overwrite A-Z,a-z,0-9,-,.,_
+                            ;;
+                        * )                                                         # do this in all other cases
+                            echo -e " \e[1m Packages have not been updated.\e[0m"
+                            ;;
+                    esac
+
+                fi
+
+            else
+
+                # print error message, if there is no connection to a mirror/repository server and quit
+                echo
+                echo -e " \e[41m Either there is something wrong with your internet connection or with your mirror/repository server: $server \e[0m"        # writing the $server variables in quotes (" or ') does not work! using ' for echo command does not work either!
+                echo -e " \e[1;41m Please make sure both are ok and rerun this part of PacUI! \e[0m"
+                echo
+
+            fi
+
+        fi
+}
+#
 # AUR Helper
 AUR_Helper="$PACUI_AUR_HELPER"
 
@@ -139,6 +277,37 @@ packages=("snapd" "flatpak");
 #Or,
 #_installMany "lshw" "inkscape"
 #====================================================================#
+#
+# Pamac update if pamac-common is installed
+_isInstalled_pamac() {
+    package="pamac-common";
+    check="$(sudo pacman -Qs --color always "${package}" | grep "local" | grep "${package} ")";
+    if [ -n "${check}" ] ; then
+        echo 0; #'0' means 'true' in Bash
+        return; #true
+    fi;
+    echo 1; #'1' means 'false' in Bash
+    return; #false
+}
+# `_install <pkg>`
+_pamac() {
+    package="pamac-common";
+
+    # If the package IS installed:
+    if [[ $(_isInstalled_pamac "${package}") == 0 ]]; then
+        pamac update -a;
+        return;
+    fi;
+
+    # If the package is NOT installed:
+    if [[ $(_isInstalled_pamac "${package}") == 1 ]]; then
+        echo "";
+        echo "${package} is not installed, trying AUR Helpers ...";
+        echo "";
+        _update;
+    fi;
+}
+#
 # check for database lock file before update
 _db_check(){
     echo " checking for database lock file ... "
@@ -160,7 +329,7 @@ _update_full(){
             then
                 sudo find /var/cache/pacman/pkg/ -iname "*.part" -exec rm {} \;		 # remove partially downloaded packages
                 sudo pacman-mirrors -g -f 3 && sudo pacman -Syyu --noconfirm           # choose mirrors server (with up-to-date packages) from closest mirrors and sync database.
-                pamac update -a
+                _pamac
 
             elif [[ -f /usr/bin/reflector ]]                                        # checks, whether file "reflector" exists
             then
@@ -331,7 +500,15 @@ _update_full(){
                 echo -e " \e[1m If the(se) kernel(s) are taken from the AUR, you may safely ignore this warning. \e[0m"
                 echo "$eol_kernels"
             fi
-            echo ""
+
+            if [[ -d /tmp/pacui-aur ]]
+          	then
+              echo ""
+              echo " deleting cache ..."
+              sudo rm -r /tmp/pacui*
+
+          fi
+          echo ""
         fi
 }
 #====================================================================#
@@ -442,7 +619,7 @@ echo;
 time {
 _db_check;
 _update_full;
-_install "${package}";
+_install "meld";
 _pacdiff;
 _flatpak;
 _snapd;
